### ISSUE TITLE
License för sidans kod?

### ISSUE THREAD

**Issue by Doctor-love** [gnistor-se/gnistor#30]
Jag är intresserad av att använda koden från repot för att sätta upp en liknande eventsida för livespelningar.
Kan dock inte hitta vilken license, om någon, koden släpps under. Kan ni förtydliga detta?

**Comment by redundans** [comment]
Hej @Doctor-love låter som ett kul projekt. Jag har lagt till en LICENSE-fil i projektet nu som hänvisar till [unlicense](https://unlicense.org/). Så det finns inga krav på motprestationer i form av tillskrivning eller hur koden får användas av andra.

Har aldrig tänkt att koden skall kunna användas av andra. Så om du har förslag på förändringar som skulle kunna underlätta att kodbasen delas av fler projekt så skapa en issue om hur vetja.

Rock on! 🤘
