### ISSUE TITLE
Förekomsten av `&amp;` i ICS genererat matrial

### ISSUE THREAD

**Issue by johanbluecreek** [gnistor-se/gnistor#42]
Det verkar som att de event-entries som genereras till ICS-länken, https://www.gnistor.se/ics/index.ics, tar med sig html-enkodade och-tecken: `&amp;`. Dessa verkar inte stödjas av ical läsare av olika slag. Om jag t.ex. importerar ics filen i `calcurse` så markerar den alla med en `&amp;` i sitt `SUMMARY`-fält som oläsbara. Rättar jag dessa så går de att läsa in. Om jag subscribe:ar på länken på mobilen i Appen ICSx5 få får jag ett felmeddelande, och om jag manipulerar filen manuellt genom att ta bort `&amp;` ur ett `ORGANIZER` fält så kan det läsas in. Så felet är lite olika, calcurse klagar bara på `SYMMARY`, och ICSx5 bara på  `ORGANIZER`, men det gemenasamma är förekomsten av `&amp;`. Skulle det gå att skriva om ICS-genereringen till att inte push:a HTML-kodade strängar?

**Comment by redundans** [comment]
Bra funnet. Jag provar att skriva ut organizer och title med filtret safeHTML nu. Kolla om det fungerar bättre i din klient.

**Comment by johanbluecreek** [comment]
Tack! Funkar super. Lyckades lägga in Gnistor ics:en i min kalender med ICSx5 nu.
